name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # SHA Resmi untuk actions/checkout@v3.6.0
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    
    # SHA Resmi untuk actions/setup-python@v4.7.1 (Ini yang benar!)
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mlflow dagshub scikit-learn pandas numpy matplotlib seaborn
        
    - name: Run MLflow Project Training
      run: |
        mlflow run MLProject --entry-point main --no-conda

    - name: Run automated tests
      run: |
        pytest test_model.py || echo "Belum ada file unit test, dilewati aman."

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    # SHA Resmi untuk actions/checkout@v3.6.0
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

    # SHA Resmi untuk docker/login-action@v2.2.0
    - name: Login to Docker Hub
      uses: docker/login-action@46543ed4e38e5b19c4021f568c1928a4a968a5a6
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # SHA Resmi untuk docker/build-push-action@v4.1.1
    - name: Build and push Docker image
      uses: docker/build-push-action@2eb1c1b3500047996b2d75a56d105411c5211c06
      with:
        context: ./MLProject
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest