name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    
    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5fe4f3d0024db2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mlflow dagshub scikit-learn pandas numpy matplotlib seaborn
        
    - name: Run MLflow Project Training
      run: |
        mlflow run MLProject --entry-point main --no-conda

    - name: Run automated tests
      run: |
        pytest test_model.py || echo "Belum ada file unit test, dilewati aman."

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

    - name: Login to Docker Hub
      uses: docker/login-action@46543ed4e38e5b19c4021f568c1928a4a968a5a6
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@2eb1c1b3500047996b2d75a56d105411c5211c06
      with:
        context: ./MLProject
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest